# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: examples/proto/user_joined.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    "",
    "examples/proto/user_joined.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n examples/proto/user_joined.proto"\xa9\x01\n\x0eUserJoinedECST\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12(\n\x07payload\x18\x06 \x01(\x0b\x32\x17.UserJoinedECST.Payload\x1a.\n\x07Payload\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nmeeting_id\x18\x02 \x01(\t"\xb9\x01\n\x16UserJoinedNotification\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x30\n\x07payload\x18\x06 \x01(\x0b\x32\x1f.UserJoinedNotification.Payload\x1a.\n\x07Payload\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nmeeting_id\x18\x02 \x01(\tb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "examples.proto.user_joined_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERJOINEDECST"]._serialized_start = 37
    _globals["_USERJOINEDECST"]._serialized_end = 206
    _globals["_USERJOINEDECST_PAYLOAD"]._serialized_start = 160
    _globals["_USERJOINEDECST_PAYLOAD"]._serialized_end = 206
    _globals["_USERJOINEDNOTIFICATION"]._serialized_start = 209
    _globals["_USERJOINEDNOTIFICATION"]._serialized_end = 394
    _globals["_USERJOINEDNOTIFICATION_PAYLOAD"]._serialized_start = 160
    _globals["_USERJOINEDNOTIFICATION_PAYLOAD"]._serialized_end = 206
# @@protoc_insertion_point(module_scope)
